import styles from "../styles/index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (

    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.introcontainer}>
          <div className={styles.infopic}>Bild 1</div>
          <div className={styles.infopic}>Bild 2</div>
          <div className={styles.infopic}>Bild 3</div>
        </div>
        <div className={styles.secondcontainer}>
          <div className={styles.circleitemcontainer}></div>
        </div>
      </main>
    </>
  );
};

export default Home;
